# Generated by Django 3.1.3 on 2020-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('trello_id', models.CharField(max_length=24, verbose_name='Trello Id')),
            ],
        ),
        migrations.CreateModel(
            name='TrelloCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Card title')),
                ('trello_id', models.CharField(max_length=24, verbose_name='Trello Id')),
                ('url', models.CharField(max_length=500, verbose_name='Card link')),
            ],
        ),
        migrations.CreateModel(
            name='TrelloList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('trello_id', models.CharField(max_length=24, verbose_name='Trello Id')),
            ],
        ),
    ]
