# Generated by Django 3.1.3 on 2020-11-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0003_trellocard_trello_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='trelloboard',
            name='url',
            field=models.CharField(max_length=500, null=True, verbose_name='Link'),
        ),
    ]
