# Generated by Django 3.1.3 on 2020-11-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0007_auto_20201127_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('trello_id', models.CharField(max_length=24, verbose_name='Trello Id')),
                ('creatio_id', models.CharField(max_length=36, null=True, verbose_name='Creatio Id')),
            ],
        ),
        migrations.AddField(
            model_name='creatioreceipt',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.trelloboard'),
        ),
        migrations.CreateModel(
            name='ExecutorInCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hours')),
                ('minutes', models.IntegerField(verbose_name='Minutes')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.trellocard')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.executor')),
            ],
        ),
        migrations.AddField(
            model_name='trellocard',
            name='executors',
            field=models.ManyToManyField(through='trello_to_receipt.ExecutorInCard', to='trello_to_receipt.Executor'),
        ),
    ]
