# Generated by Django 3.1.3 on 2020-11-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0009_executor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellocard',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.creatioreceipt'),
        ),
    ]
