# Generated by Django 3.1.3 on 2020-11-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0010_trellocard_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trelloboard',
            name='trello_id',
            field=models.CharField(max_length=24, unique=True, verbose_name='Trello Id'),
        ),
    ]
