# Generated by Django 3.1.3 on 2020-11-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0011_auto_20201129_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='trellolist',
            name='board_trello_id',
            field=models.CharField(max_length=24, null=True, verbose_name='Parent Board Id'),
        ),
        migrations.AlterField(
            model_name='trellolist',
            name='trello_id',
            field=models.CharField(max_length=24, unique=True, verbose_name='Trello Id'),
        ),
    ]
