# Generated by Django 3.1.3 on 2020-11-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0012_auto_20201129_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executorincard',
            name='hours',
            field=models.IntegerField(verbose_name='Hours'),
        ),
    ]
