# Generated by Django 3.1.3 on 2020-12-07 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0013_auto_20201130_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatioreceipt',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.trellolist'),
        ),
    ]
