# Generated by Django 3.1.3 on 2020-12-07 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello_to_receipt', '0014_auto_20201207_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatioreceipt',
            name='trello_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.trellolist'),
        ),
        migrations.AlterField(
            model_name='creatioreceipt',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trello_to_receipt.trelloboard'),
        ),
    ]
